export const env = {
  AUTH0_SECRET: process.env.AUTH0_SECRET!,
  AUTH0_BASE_URL: process.env.AUTH0_BASE_URL!,
  AUTH0_ISSUER_BASE_URL: process.env.AUTH0_ISSUER_BASE_URL!,
  AUTH0_CLIENT_ID: process.env.AUTH0_CLIENT_ID!,
  AUTH0_CLIENT_SECRET: process.env.AUTH0_CLIENT_SECRET!,
  AUTH0_CUSTOM_CLAIMS_URI: process.env.AUTH0_CUSTOM_CLAIMS_URI!,

  APP_URL: process.env.APP_URL!,
  MONGODB_URI: process.env.MONGODB_URI!,

  GOOGLE_PRIVATE_KEY: process.env.GOOGLE_PRIVATE_KEY!.replace(/\\n/g, '\n'),
  GOOGLE_CLIENT_EMAIL: process.env.GOOGLE_CLIENT_EMAIL!,
  SHEET_ID: process.env.SHEET_ID!,
  SHEET_NAME: process.env.SHEET_NAME!,

  MY_AWS_REGION: process.env.MY_AWS_REGION!,
  MY_AWS_ACCESS_KEY_ID: process.env.MY_AWS_ACCESS_KEY_ID!,
  MY_AWS_SECRET_ACCESS_KEY: process.env.MY_AWS_SECRET_ACCESS_KEY!,
  MY_AWS_S3_BUCKET_NAME: process.env.MY_AWS_S3_BUCKET_NAME!,

  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY!,
};
